#!/bin/bash

# Get the name of the C file from the command line argument
CFILE=$1

# Create the name of the output file by replacing the extension
ASMFILE="${CFILE%.c}.s"

# Compile the C file to assembly code using GCC
gcc -S -masm=intel "$CFILE" -o "$ASMFILE"

